name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Run type check
        run: yarn compile

      - name: Run linter
        run: yarn lint

      - name: Run spell check
        run: yarn spell-check

      - name: Test build
        run: yarn build:electron
